const fighters=[{id:'freddy',name:'Freddy Fazbear',universe:"Five Nights at Freddy's",rarity:'common',health:105,attack:16,move:'Mic Slam'},{id:'chica',name:'Chica',universe:"Five Nights at Freddy's",rarity:'common',health:96,attack:15,move:'Rapid Bite'},{id:'bonnie',name:'Bonnie',universe:"Five Nights at Freddy's",rarity:'rare',health:110,attack:18,move:'Crushing Hook'},{id:'foxy',name:'Foxy',universe:"Five Nights at Freddy's",rarity:'rare',health:104,attack:19,move:'Pirate Rush'},{id:'golden',name:'Golden Freddy',universe:"Five Nights at Freddy's",rarity:'legendary',health:125,attack:26,move:'Phantom Burst'},{id:'iron',name:'Iron Man',universe:'Marvel',rarity:'rare',health:108,attack:20,move:'Repulsor Beam'},{id:'spider',name:'Spider-Man',universe:'Marvel',rarity:'epic',health:112,attack:24,move:'Web Combo'},{id:'hulk',name:'Hulk',universe:'Marvel',rarity:'legendary',health:138,attack:28,move:'Gamma Smash'},{id:'thor',name:'Thor',universe:'Marvel',rarity:'epic',health:122,attack:25,move:'Stormbreaker'},{id:'batman',name:'Batman',universe:'DC',rarity:'rare',health:116,attack:22,move:'Batarang Rain'},{id:'superman',name:'Superman',universe:'DC',rarity:'legendary',health:132,attack:30,move:'Solar Blast'},{id:'flash',name:'Flash',universe:'DC',rarity:'epic',health:104,attack:23,move:'Speed Burst'},{id:'scorpion',name:'Scorpion',universe:'Mortal Kombat',rarity:'epic',health:116,attack:24,move:'Toasty Spear'},{id:'subzero',name:'Sub-Zero',universe:'Mortal Kombat',rarity:'rare',health:114,attack:21,move:'Frost Breaker'},{id:'raiden',name:'Raiden',universe:'Mortal Kombat',rarity:'mythic',health:140,attack:33,move:'Thunder Storm'}];
const packs=[{id:'fnaf',name:'FNAF Pack',group:"Five Nights at Freddy's",cost:40},{id:'marvel',name:'Marvel Pack',group:'Marvel',cost:50},{id:'dc',name:'DC Pack',group:'DC',cost:55},{id:'mk',name:'Mortal Kombat Pack',group:'Mortal Kombat',cost:60}];
const sentences=['I will never back down from this fight.','Every strike I land makes them weaker.','Victory belongs to the fighter who keeps moving.','My courage fuels each attack and every step.','The arena shakes as I take control.','I move with purpose and fight for the win.','My focus is sharp and my timing is true.'];
const state={coins:120,owned:['freddy'],selected:'freddy',battle:null,topWpm:0,avgWpm:0,wpm:[],combo:'normal',started:false};
const $=id=>document.getElementById(id);const selected=()=>fighters.find(f=>f.id===state.selected)||fighters[0];
function save(){localStorage.setItem('typefight-save',JSON.stringify(state));toast('Game saved!')}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('typefight-save')||'{}'))}catch(e){toast('No save found')}}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function rarity(){let n=Math.random()*100;return n<58?'common':n<83?'rare':n<94?'epic':n<98?'legendary':'mythic'}function packCard(group){let pool=fighters.filter(f=>f.universe===group),r=rarity(),same=pool.filter(f=>f.rarity===r);return (same.length?same:pool)[Math.floor(Math.random()*(same.length||pool.length))]}
function renderRoster(){let box=$('rosterList');box.innerHTML='';fighters.filter(f=>state.owned.includes(f.id)).forEach(f=>{let el=document.createElement('div');el.className='fighter-item '+(f.id===state.selected?'selected':'');el.innerHTML=`<div class="fighter-main"><span class="fighter-name">${f.name}</span><span class="fighter-meta">${f.universe}</span></div><span class="rarity-badge rarity-${f.rarity}">${f.rarity}</span>`;el.onclick=()=>{state.selected=f.id;render();if(!state.battle)startBattle()};box.appendChild(el)})}
function renderPacks(){let box=$('packList');box.innerHTML='';packs.forEach(p=>{let el=document.createElement('div');el.className='pack-item';el.innerHTML=`<div class="pack-head"><span>${p.name}</span><span class="pack-price">${p.cost} coins</span></div><div class="pack-meta">${p.group}</div><div class="pack-buttons"></div>`;[1,3,5].forEach(n=>{let b=document.createElement('button');b.className='buy-btn';b.textContent='Buy '+n;b.onclick=()=>buy(p,n);el.querySelector('.pack-buttons').appendChild(b)});box.appendChild(el)})}
function renderCollection(){let box=$('collectionList');box.innerHTML='';fighters.filter(f=>state.owned.includes(f.id)).forEach(f=>{let el=document.createElement('div');el.className='collection-card rarity-'+f.rarity;el.innerHTML=`<div class="meta"><span class="rarity-badge rarity-${f.rarity}">${f.rarity}</span><span>${f.universe}</span></div><h3>${f.name}</h3><div class="meta"><span>HP ${f.health}</span><span>ATK ${f.attack}</span></div><div class="pull-tag">${f.id==='freddy'?'STARTER':'COLLECTED'}</div>`;box.appendChild(el)})}
function reveal(f){$('revealName').textContent=f.name;$('revealUniverse').textContent=f.universe;$('revealRarity').textContent=f.rarity.toUpperCase();$('revealHp').textContent=f.health;$('revealAttack').textContent=f.attack;$('revealCard').className='reveal-card rarity-'+f.rarity;$('packRevealOverlay').classList.remove('hidden');setTimeout(()=>$('packRevealOverlay').classList.add('hidden'),2200)}
function buy(pack,n){let cost=pack.cost*n;if(state.coins<cost)return toast('Not enough coins!');state.coins-=cost;for(let i=0;i<n;i++){let f=packCard(pack.group);if(!state.owned.includes(f.id)){state.owned.push(f.id);reveal(f)}else state.coins+=Math.floor(pack.cost*.4)}saveSilent();render();toast('Pack opened!')}
function sentence(){state.battle.sentence=sentences[Math.floor(Math.random()*sentences.length)];state.battle.started=Date.now();$('typingInput').value='';drawSentence()}
function startBattle(){let p=selected(),pool=fighters.filter(f=>f.id!==p.id),e=pool[Math.floor(Math.random()*pool.length)];state.battle={player:p.id,enemy:e.id,ph:p.health,eh:e.health,pm:p.health,em:e.health};$('playerNamePlate').textContent=p.name;$('enemyNamePlate').textContent=e.name;$('moveTag').textContent='Move: '+p.move;$('enemyHealthText').textContent=e.health+' / '+e.health;sentence();health();$('battleLog').textContent=p.name+' has been summoned against '+e.name+'!'}
function drawSentence(){let s=state.battle?.sentence||'';let typed=$('typingInput').value; $('sentenceBox').innerHTML=[...s].map((c,i)=>`<span class="${i<typed.length?(typed[i]===c?'correct':'wrong'):''}">${c}</span>`).join('')}
function health(){if(!state.battle)return;$('playerHealthFill').style.width=Math.max(0,state.battle.ph/state.battle.pm*100)+'%';$('enemyHealthFill').style.width=Math.max(0,state.battle.eh/state.battle.em*100)+'%';$('playerHealthText').textContent=Math.max(0,state.battle.ph)+' / '+state.battle.pm;$('enemyHealthText').textContent=Math.max(0,state.battle.eh)+' / '+state.battle.em}
function attack(){if(!state.battle)return startBattle();let text=$('typingInput').value,s=state.battle.sentence;if(!text.trim())return toast('Type the sentence first!');let correct=[...text].filter((c,i)=>c===s[i]).length,accuracy=correct/s.length,ratio=text.length/s.length,mult=state.combo==='special'?1.8:state.combo==='combo'?1.35:1,p=selected(),damage=Math.max(5,Math.round((p.attack+({common:0,rare:12,epic:24,legendary:38,mythic:54}[p.rarity]||0))*(.4+accuracy*1.8+ratio*.8)*mult));state.battle.eh-=damage;$('battleLog').textContent=p.name+' uses '+p.move+' for '+damage+' damage!';if(state.battle.eh<=0){state.coins+=35+Math.floor(Math.random()*30);let mins=Math.max((Date.now()-state.battle.started)/60000,.05),wpm=correct/5/mins;state.wpm.push(wpm);state.topWpm=Math.max(state.topWpm,wpm);state.avgWpm=state.wpm.reduce((a,b)=>a+b,0)/state.wpm.length;state.battle=null;render();toast('Victory! Coins earned.');return}state.battle.ph-=Math.max(8,Math.round((fighters.find(f=>f.id===state.battle.enemy).attack)*(.7+Math.random())));health();if(state.battle.ph<=0){state.battle=null;$('battleLog').textContent='Defeat. Summon again and try a faster, cleaner sentence.';render();return}sentence();renderStats();saveSilent()}
function renderStats(){$('coinCount').textContent=state.coins;$('topWpmStat').textContent=(state.topWpm||0).toFixed(1);$('avgWpmStat').textContent=(state.avgWpm||0).toFixed(1);$('introTopWpm').textContent=(state.topWpm||0).toFixed(1);$('introAvgWpm').textContent=(state.avgWpm||0).toFixed(1)}function saveSilent(){localStorage.setItem('typefight-save',JSON.stringify(state))}
function render(){renderStats();renderRoster();renderPacks();renderCollection();document.querySelectorAll('.combo-btn').forEach(b=>b.classList.toggle('active',b.dataset.combo===state.combo));if(state.battle)health();else $('sentenceBox').textContent='Start a battle to begin typing.'}
function init(){load();if(!state.owned.includes('freddy'))state.owned=['freddy',...state.owned];$('startBtn').onclick=()=>{$('introScreen').classList.add('hidden');$('gameRoot').classList.remove('hidden');state.started=true;startBattle()};$('newBattleBtn').onclick=startBattle;$('attackBtn').onclick=attack;$('typingInput').oninput=drawSentence;$('typingInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();attack()}};document.querySelectorAll('.combo-btn').forEach(b=>b.onclick=()=>{state.combo=b.dataset.combo;$('moveBoost').textContent='Combo: '+state.combo.toUpperCase();render()});$('saveBtn').onclick=save;$('loadBtn').onclick=()=>{load();render();toast('Game loaded!')};render();if(state.started){$('introScreen').classList.add('hidden');$('gameRoot').classList.remove('hidden');startBattle()}}init();